"""Injectable application service objects."""

from __future__ import annotations

from importlib import import_module

__all__ = [
    "DaemonService",
    "DaemonStateService",
    "DaemonLaneUpdate",
    "DaemonUpdateBatch",
    "DaemonUpdateSubscription",
    "CatalogPort",
    "CatalogQueryService",
    "CommandPort",
    "FlowCatalogService",
    "FlowExecutionService",
    "FlowConfigPreview",
    "FlowCatalogItem",
    "ForceShutdownCommandResult",
    "HistoryPort",
    "HistoryQueryService",
    "LedgerService",
    "LogService",
    "OperatorCommandResult",
    "OperatorCommandService",
    "ProvisionWorkspaceCommandResult",
    "RefreshFlowsCommandResult",
    "ResetFlowCommandResult",
    "ResetWorkspaceCommandResult",
    "RuntimeExecutionService",
    "RuntimeIoCacheStore",
    "RuntimeIoLayer",
    "ResetService",
    "IncrementalDaemonProjection",
    "flow_state_texts_from_workspace_snapshot",
    "RuntimeStatePort",
    "RuntimeStateService",
    "flow_state_text_from_live_summary",
    "runtime_session_from_workspace_snapshot",
    "WorkspaceSnapshot",
    "WorkspaceRuntimeBinding",
    "WorkspaceRuntimeBindingService",
    "RuntimeHistoryService",
    "SettingsService",
    "SharedStateService",
    "ThemeService",
    "WorkspaceProvisioningService",
    "WorkspaceService",
]

_SERVICE_MODULES = {
    "DaemonService": "data_engine.services.daemon",
    "DaemonStateService": "data_engine.services.daemon_state",
    "DaemonLaneUpdate": "data_engine.services.daemon_state",
    "DaemonUpdateBatch": "data_engine.services.daemon_state",
    "DaemonUpdateSubscription": "data_engine.services.daemon_state",
    "CatalogPort": "data_engine.services.operator_queries",
    "CatalogQueryService": "data_engine.services.operator_queries",
    "CommandPort": "data_engine.services.operator_commands",
    "FlowCatalogService": "data_engine.services.flow_catalog",
    "FlowExecutionService": "data_engine.services.flow_execution",
    "FlowConfigPreview": "data_engine.services.operator_queries",
    "FlowCatalogItem": "data_engine.services.operator_queries",
    "ForceShutdownCommandResult": "data_engine.services.operator_commands",
    "HistoryPort": "data_engine.services.operator_queries",
    "HistoryQueryService": "data_engine.services.operator_queries",
    "LedgerService": "data_engine.services.ledger",
    "LogService": "data_engine.services.logs",
    "OperatorCommandResult": "data_engine.services.operator_commands",
    "OperatorCommandService": "data_engine.services.operator_commands",
    "ProvisionWorkspaceCommandResult": "data_engine.services.operator_commands",
    "RefreshFlowsCommandResult": "data_engine.services.operator_commands",
    "ResetFlowCommandResult": "data_engine.services.operator_commands",
    "ResetWorkspaceCommandResult": "data_engine.services.operator_commands",
    "RuntimeExecutionService": "data_engine.services.runtime_execution",
    "RuntimeIoCacheStore": "data_engine.services.runtime_io",
    "RuntimeIoLayer": "data_engine.services.runtime_io",
    "ResetService": "data_engine.services.reset",
    "IncrementalDaemonProjection": "data_engine.services.runtime_state",
    "flow_state_texts_from_workspace_snapshot": "data_engine.services.runtime_state",
    "RuntimeStatePort": "data_engine.services.runtime_state",
    "RuntimeStateService": "data_engine.services.runtime_state",
    "flow_state_text_from_live_summary": "data_engine.services.runtime_state",
    "runtime_session_from_workspace_snapshot": "data_engine.services.runtime_state",
    "WorkspaceSnapshot": "data_engine.services.runtime_state",
    "WorkspaceRuntimeBinding": "data_engine.services.runtime_binding",
    "WorkspaceRuntimeBindingService": "data_engine.services.runtime_binding",
    "RuntimeHistoryService": "data_engine.services.runtime_history",
    "SettingsService": "data_engine.services.settings",
    "SharedStateService": "data_engine.services.shared_state",
    "ThemeService": "data_engine.services.theme",
    "WorkspaceProvisioningService": "data_engine.services.workspace_provisioning",
    "WorkspaceService": "data_engine.services.workspaces",
}


def __getattr__(name: str):
    module_name = _SERVICE_MODULES.get(name)
    if module_name is None:
        raise AttributeError(name)
    module = import_module(module_name)
    return getattr(module, name)
