"""Shared daemon host constants."""

from data_engine.platform.identity import APP_VERSION

CHECKPOINT_INTERVAL_SECONDS = 30.0
CONTROL_REQUEST_POLL_INTERVAL_SECONDS = 1.0
STALE_AFTER_SECONDS = 90.0

__all__ = [
    "APP_VERSION",
    "CHECKPOINT_INTERVAL_SECONDS",
    "CONTROL_REQUEST_POLL_INTERVAL_SECONDS",
    "STALE_AFTER_SECONDS",
]
