"""Shared daemon host constants."""

APP_VERSION = "0.1.0"
CHECKPOINT_INTERVAL_SECONDS = 30.0
CONTROL_REQUEST_POLL_INTERVAL_SECONDS = 1.0
STALE_AFTER_SECONDS = 90.0
DAEMON_STARTUP_LOCK_STALE_SECONDS = 15.0

__all__ = [
    "APP_VERSION",
    "CHECKPOINT_INTERVAL_SECONDS",
    "CONTROL_REQUEST_POLL_INTERVAL_SECONDS",
    "DAEMON_STARTUP_LOCK_STALE_SECONDS",
    "STALE_AFTER_SECONDS",
]
