#!/usr/bin/env python3
"""Create a single self-extracting Python script for project transfer."""

from __future__ import annotations

import argparse
import base64
import io
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

VALID_BUNDLE_KINDS = ("full", "code", "tests")

DEFAULT_EXCLUDE_PARTS = {
    ".git",
    ".venv",
    ".pytest_cache",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "transfer_chunks",
}

DEFAULT_EXCLUDE_PREFIXES = (
    "documentation/_build/",
    "documentation/.DS_Store",
)
PROJECT_EXCLUDE_PREFIXES = (
    "artifacts/",
)

CODE_EXCLUDE_PREFIXES = (
    "tests/",
)

TEST_ONLY_INCLUDE_PREFIXES = (
    "tests/",
)

SCRIPT_TEMPLATE = """#!/usr/bin/env python3
\"\"\"Self-extracting project bundle generated by export_project_bundle_script.py.\"\"\"

from __future__ import annotations

import argparse
import base64
import io
from pathlib import Path
from zipfile import ZipFile


ARCHIVE_BASE64 = \"\"\"{archive_base64}\"\"\"


def parse_args() -> argparse.Namespace:
    '''Parse CLI arguments for building a self-extracting project bundle.'''
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("{default_output_dir}"),
        help="Directory where the project will be extracted.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Allow existing files to be overwritten.",
    )
    return parser.parse_args()


def main() -> None:
    '''Render and write the self-extracting bundle script to disk.'''
    args = parse_args()
    output_dir = args.output_dir.expanduser().resolve()
    workspaces_dir = output_dir.parent / "workspaces"
    repo_workspace_path = output_dir.parent / "repo.code-workspace"
    archive_bytes = base64.b64decode(ARCHIVE_BASE64.encode("ascii"))
    extracted = 0

    with ZipFile(io.BytesIO(archive_bytes)) as archive:
        for member in archive.infolist():
            if member.is_dir():
                continue
            member_path = Path(member.filename)
            if member_path.parts and member_path.parts[0] == "workspaces":
                relative_member = Path(*member_path.parts[1:])
                target = (workspaces_dir / relative_member).resolve()
                safe_root = workspaces_dir.resolve()
            elif member_path.name == "repo.code-workspace":
                target = repo_workspace_path.resolve()
                safe_root = output_dir.parent.resolve()
            else:
                target = (output_dir / member_path).resolve()
                safe_root = output_dir.resolve()
            try:
                target.relative_to(safe_root)
            except ValueError as exc:
                raise SystemExit(f"Unsafe archive member path: {{member.filename}}") from exc
            if target.exists() and not args.overwrite:
                raise SystemExit(f"Refusing to overwrite existing file: {{target}}")
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(archive.read(member))
            mode = (member.external_attr >> 16) & 0o777
            if mode:
                target.chmod(mode)
            extracted += 1

    print(f"Extracted {{extracted}} files into {{output_dir}}")


if __name__ == "__main__":
    main()
"""


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for the bundle exporter itself."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Project root to bundle. Defaults to the current working directory.",
    )
    parser.add_argument(
        "--output-file",
        type=Path,
        default=Path("project_bundle.py"),
        help="Destination for the generated self-extracting Python script.",
    )
    parser.add_argument(
        "--default-output-dir",
        default="reconstructed_project",
        help="Default extraction directory baked into the generated script.",
    )
    parser.add_argument(
        "--bundle-kind",
        choices=VALID_BUNDLE_KINDS,
        default="full",
        help="Which subset to export: full project, code only, or tests only.",
    )
    parser.add_argument(
        "--workspace-id",
        default="example_workspace",
        help="Sibling workspace id to include in non-test bundles. Defaults to 'example_workspace'.",
    )
    return parser.parse_args()


def main() -> None:
    """Build the archive payload and write the generated bundle script."""
    args = parse_args()
    root = args.root.expanduser().resolve()
    output_file = args.output_file.expanduser().resolve()

    if not root.is_dir():
        raise SystemExit(f"Project root does not exist: {root}")

    archive_bytes = build_archive(
        root=root,
        output_file=output_file,
        bundle_kind=args.bundle_kind,
        workspace_id=args.workspace_id,
    )
    rendered = SCRIPT_TEMPLATE.format(
        archive_base64=base64.b64encode(archive_bytes).decode("ascii"),
        default_output_dir=args.default_output_dir,
    )
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(rendered, encoding="utf-8")
    print(f"Wrote self-extracting bundle to {output_file}")


def build_archive(*, root: Path, output_file: Path, bundle_kind: str = "full", workspace_id: str = "example_workspace") -> bytes:
    """Return the zipped project payload embedded into the generated script."""
    if bundle_kind not in VALID_BUNDLE_KINDS:
        raise ValueError(f"Unsupported bundle kind: {bundle_kind}")
    buffer = io.BytesIO()
    excluded_output = output_file if output_file.is_absolute() else (root / output_file).resolve()
    repo_workspace_file = root.parent / "repo.code-workspace"

    with ZipFile(buffer, "w", compression=ZIP_DEFLATED) as archive:
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            if should_skip(path=path, root=root, excluded_output=excluded_output, bundle_kind=bundle_kind):
                continue
            archive.write(path, path.relative_to(root).as_posix())
        if bundle_kind != "tests" and repo_workspace_file.is_file():
            archive.write(repo_workspace_file, repo_workspace_file.name)
    return buffer.getvalue()


def should_skip(*, path: Path, root: Path, excluded_output: Path, bundle_kind: str) -> bool:
    """Return whether one project file should be excluded from the bundle."""
    relative_path = path.relative_to(root)
    if any(part in DEFAULT_EXCLUDE_PARTS for part in relative_path.parts):
        return True
    if path.name in {".DS_Store", ".coverage"}:
        return True
    relative_name = relative_path.as_posix()
    if any(relative_name.startswith(prefix) for prefix in DEFAULT_EXCLUDE_PREFIXES):
        return True
    if any(relative_name.startswith(prefix) for prefix in PROJECT_EXCLUDE_PREFIXES):
        return True
    if bundle_kind == "code" and any(relative_name.startswith(prefix) for prefix in CODE_EXCLUDE_PREFIXES):
        return True
    if bundle_kind == "tests" and not any(
        relative_name == prefix.removesuffix("/") or relative_name.startswith(prefix)
        for prefix in TEST_ONLY_INCLUDE_PREFIXES
    ):
        return True
    try:
        path.resolve().relative_to(excluded_output)
        return True
    except ValueError:
        return False
if __name__ == "__main__":
    main()
